-- Core schema — portable SQL for PostgreSQL (prod) and H2 (dev).

CREATE TABLE persons (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name VARCHAR(255) NOT NULL,
    created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE lab_reports (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id         BIGINT NOT NULL REFERENCES persons(id),
    original_filename VARCHAR(512) NOT NULL,
    storage_path      VARCHAR(1024) NOT NULL,
    report_date       DATE,
    lab_name          VARCHAR(255),
    uploaded_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_lab_reports_person_id ON lab_reports(person_id);
