-- Extraction pipeline: status on reports + structured biomarker values.

ALTER TABLE lab_reports ADD COLUMN extraction_status VARCHAR(32) NOT NULL DEFAULT 'PENDING';
ALTER TABLE lab_reports ADD COLUMN extracted_text CLOB;
ALTER TABLE lab_reports ADD COLUMN extraction_error VARCHAR(1024);
ALTER TABLE lab_reports ADD COLUMN extracted_at TIMESTAMP;

CREATE TABLE biomarker_values (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lab_report_id   BIGINT NOT NULL REFERENCES lab_reports(id),
    canonical_name  VARCHAR(128) NOT NULL,
    raw_test_name   VARCHAR(255),
    numeric_value   DECIMAL(14, 4),
    text_value      VARCHAR(255),
    unit            VARCHAR(64),
    reference_range VARCHAR(128),
    confidence      DECIMAL(5, 4),
    source_page     INT,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_biomarker_values_report_id ON biomarker_values(lab_report_id);
