spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:file:${user.home}/.phi/h2db;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

logging:
  level:
    com.phi: DEBUG
